/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'isReaction' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface Player {
  'id' : Principal,
  'name' : string,
  'hasFinished' : boolean,
  'score' : [] | [bigint],
  'finishTime' : [] | [bigint],
}
export interface RoomState {
  'allFinished' : boolean,
  'players' : Array<Player>,
}
export interface ScoreEntry { 'name' : string, 'score' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanExpiredRooms' : ActorMethod<[], undefined>,
  'createRoom' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getLeaderboard' : ActorMethod<[], Array<ScoreEntry>>,
  'getPersonalBest' : ActorMethod<[], [] | [ScoreEntry]>,
  'getRoomPlayers' : ActorMethod<[string], Array<Player>>,
  'getRoomState' : ActorMethod<[string], RoomState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRoomActive' : ActorMethod<[string], boolean>,
  'joinRoom' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string, string], undefined>,
  'sendReaction' : ActorMethod<[string, string], undefined>,
  'submitRaceScore' : ActorMethod<[string, bigint, bigint], undefined>,
  'submitScore' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];